# more GitHub Actions steps above...
- name: Run unit tests
  env:
    REACT_APP_ACCESS_TOKEN: ${{secrets.REACT_APP_ACCESS_TOKEN}}
  run: yarn test:coverage
- run: yarn lint
- name: Cypress run # our e2e tests
  uses: cypress-io/github-action@v2
  with:
    env: configFile=staging
    start: yarn start
  env:
    REACT_APP_ACCESS_TOKEN: ${{secrets.REACT_APP_ACCESS_TOKEN}}
# more GitHub Actions steps below...
